# Path: /mnt/nvme-4tb/electrs/config.toml
# Electrs-romanz v0.10.10 Konfiguration
network = "bitcoin"

# Bitcoin Core Verbindung
daemon_rpc_addr = "127.0.0.1:8332"
daemon_p2p_addr = "127.0.0.1:8333"
cookie_file = "/mnt/nvme-4tb/bitcoin/.cookie"

# Electrs Server
electrum_rpc_addr = "0.0.0.0:50001"
monitoring_addr = "127.0.0.1:4224"

# Datenbank
db_dir = "/mnt/nvme-4tb/electrs/db"

# Performance
index_batch_size = 100
jsonrpc_timeout = "60s"
wait_duration = "30s"

# Logging
log_filters = "electrs=INFO"
